// House-to-house chat backed by Supabase. Identity is the current house
// (no auth, no PIN). Anyone using this device as a given house can read
// and write that house's messages — accepted trade-off for a friendly
// neighbourhood tool.
//
// One table: `chat_messages`.
//   to_house = null    => broadcast to "Alle hus"
//   to_house = "20C"   => direct message to house 20C
//
// Read state is per device (localStorage) — switching devices resets the
// "unread" badge for that device but messages are never lost.
//
// ---------------------------------------------------------------------------
// SQL setup (run once in the Supabase SQL editor):
//
//   create table if not exists chat_messages (
//     id          bigint generated by default as identity primary key,
//     from_house  text not null,
//     to_house    text,
//     body        text not null check (length(body) > 0 and length(body) <= 2000),
//     created_at  timestamptz default now()
//   );
//   create index if not exists chat_messages_to_house_idx
//     on chat_messages (to_house, created_at desc);
//   create index if not exists chat_messages_from_house_idx
//     on chat_messages (from_house, created_at desc);
//   alter publication supabase_realtime add table chat_messages;
//
//   -- Open RLS to match the rest of this co-op site:
//   alter table chat_messages enable row level security;
//   create policy "anyone can read"   on chat_messages for select using (true);
//   create policy "anyone can insert" on chat_messages for insert with check (true);
// ---------------------------------------------------------------------------

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./supabaseConfig.js?v=1778420598";
import { getCurrentHouse, subscribeCurrentHouse } from "./currentHouse.js?v=1778420598";

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: { persistSession: false },
  realtime: { params: { eventsPerSecond: 5 } },
});

// In-memory cache of every message touching the current house
// (incoming DMs, outgoing DMs, all broadcasts). Sorted ascending by created_at.
let cache = [];
let loaded = false;
let loadPromise = null;

const listeners = new Set();
let channel = null;

function notify() {
  for (const fn of listeners) {
    try { fn(cache); } catch (err) { console.warn("[chat] listener", err); }
  }
}

export function subscribeChat(fn) {
  listeners.add(fn);
  if (loaded) {
    try { fn(cache); } catch (err) { console.warn(err); }
  }
  return () => listeners.delete(fn);
}

// Returns every message visible to `house`:
//   - sent by `house`
//   - addressed to `house`
//   - broadcast (to_house IS NULL)
async function fetchAllForHouse(house, limit = 500) {
  const { data, error } = await supabase
    .from("chat_messages")
    .select("*")
    .or(`from_house.eq.${house},to_house.eq.${house},to_house.is.null`)
    .order("created_at", { ascending: true })
    .limit(limit);
  if (error) {
    console.warn("[chat] fetchAllForHouse", error);
    return [];
  }
  return data || [];
}

export async function loadChat() {
  const house = getCurrentHouse();
  if (!house) { cache = []; loaded = true; notify(); return cache; }
  if (loadPromise) return loadPromise;
  loadPromise = fetchAllForHouse(house).then((rows) => {
    cache = rows;
    loaded = true;
    loadPromise = null;
    notify();
    return cache;
  });
  return loadPromise;
}

// Realtime: new rows that touch this house get appended to the cache.
export function startChatRealtime() {
  stopChatRealtime();
  const house = getCurrentHouse();
  if (!house) return;

  channel = supabase
    .channel("chat-messages-" + house)
    .on(
      "postgres_changes",
      { event: "INSERT", schema: "public", table: "chat_messages" },
      (payload) => {
        const row = payload.new;
        if (!isVisibleTo(row, house)) return;
        // Avoid double-insert if we already have it (we insert optimistically)
        if (cache.some((m) => m.id === row.id)) return;
        cache.push(row);
        cache.sort(
          (a, b) => Date.parse(a.created_at) - Date.parse(b.created_at)
        );
        notify();
      }
    )
    .subscribe();
}

function stopChatRealtime() {
  if (channel) {
    try { supabase.removeChannel(channel); } catch {}
    channel = null;
  }
}

function isVisibleTo(row, house) {
  return (
    row.from_house === house ||
    row.to_house === house ||
    row.to_house === null
  );
}

// Reset cache + reload + resubscribe whenever the device's house changes.
subscribeCurrentHouse(() => {
  cache = [];
  loaded = false;
  loadPromise = null;
  notify();
  loadChat().then(() => startChatRealtime());
});

// ---------- Selectors ----------

// Conversation key: null for broadcast, otherwise the OTHER house's id.
function conversationKey(row, currentHouse) {
  if (row.to_house === null) return null;
  return row.from_house === currentHouse ? row.to_house : row.from_house;
}

// All messages belonging to a single conversation, in chronological order.
export function getConversation(otherHouse) {
  const me = getCurrentHouse();
  if (!me) return [];
  if (otherHouse === null) {
    return cache.filter((r) => r.to_house === null);
  }
  return cache.filter(
    (r) =>
      (r.from_house === me && r.to_house === otherHouse) ||
      (r.from_house === otherHouse && r.to_house === me)
  );
}

// Map of conversationKey -> { last: row, unread: number }
export function getConversationSummaries() {
  const me = getCurrentHouse();
  const summary = new Map();
  if (!me) return summary;
  for (const row of cache) {
    const key = conversationKey(row, me);
    const cur = summary.get(key) || { last: null, unread: 0 };
    if (!cur.last || Date.parse(row.created_at) > Date.parse(cur.last.created_at)) {
      cur.last = row;
    }
    summary.set(key, cur);
  }
  // Apply per-conversation unread counts based on lastSeen timestamps.
  for (const [key, info] of summary) {
    info.unread = countUnread(key, me);
  }
  return summary;
}

export function getTotalUnread() {
  const summaries = getConversationSummaries();
  let total = 0;
  for (const info of summaries.values()) total += info.unread;
  return total;
}

// ---------- Writes ----------

export async function sendMessage({ toHouse, body }) {
  const me = getCurrentHouse();
  if (!me) throw new Error("Velg hus først");
  const text = (body || "").trim();
  if (!text) throw new Error("Tom melding");
  if (text.length > 2000) throw new Error("For lang melding (maks 2000 tegn)");

  const { data, error } = await supabase
    .from("chat_messages")
    .insert({ from_house: me, to_house: toHouse, body: text })
    .select()
    .single();
  if (error) throw error;

  // Optimistic insert (realtime will skip duplicate).
  if (data && !cache.some((m) => m.id === data.id)) {
    cache.push(data);
    notify();
  }
  // Sender has obviously seen their own message.
  markSeen(toHouse);
  return data;
}

// ---------- Read tracking (localStorage, per device) ----------

function lastSeenKey(house, otherHouse) {
  const tag = otherHouse === null ? "all" : otherHouse;
  return `sb.chat.lastSeen.${house}.${tag}`;
}

export function getLastSeen(otherHouse) {
  const me = getCurrentHouse();
  if (!me) return 0;
  try {
    const v = localStorage.getItem(lastSeenKey(me, otherHouse));
    return v ? Number(v) : 0;
  } catch { return 0; }
}

export function markSeen(otherHouse) {
  const me = getCurrentHouse();
  if (!me) return;
  // Only notify if there were actually unread messages — otherwise rendering
  // the conversation triggers markSeen → notify → render → markSeen … loop.
  const had = countUnread(otherHouse, me) > 0;
  try {
    localStorage.setItem(lastSeenKey(me, otherHouse), String(Date.now()));
  } catch {}
  if (had) notify();
}

function countUnread(otherHouse, me) {
  const lastSeen = getLastSeen(otherHouse);
  let n = 0;
  for (const row of cache) {
    // Don't count our own outgoing messages as unread.
    if (row.from_house === me) continue;
    // Match conversation
    if (otherHouse === null) {
      if (row.to_house !== null) continue;
    } else {
      if (row.to_house !== me || row.from_house !== otherHouse) continue;
    }
    if (Date.parse(row.created_at) > lastSeen) n++;
  }
  return n;
}

// ---------- Admin: delete operations -------------------------------------

// Delete every message in the entire chat_messages table.
export async function deleteAllMessages() {
  const { error } = await supabase
    .from("chat_messages")
    .delete()
    .gt("id", 0);
  if (error) throw error;
  cache = [];
  notify();
}

// Delete only broadcast ("Sameiet") messages.
export async function deleteBroadcastMessages() {
  const { error } = await supabase
    .from("chat_messages")
    .delete()
    .is("to_house", null);
  if (error) throw error;
  cache = cache.filter((r) => r.to_house !== null);
  notify();
}

// Delete the entire conversation between two houses (both directions).
export async function deleteConversation(houseA, houseB) {
  const { error } = await supabase
    .from("chat_messages")
    .delete()
    .or(
      `and(from_house.eq.${houseA},to_house.eq.${houseB}),` +
      `and(from_house.eq.${houseB},to_house.eq.${houseA})`
    );
  if (error) throw error;
  cache = cache.filter((r) => {
    const isAB = r.from_house === houseA && r.to_house === houseB;
    const isBA = r.from_house === houseB && r.to_house === houseA;
    return !isAB && !isBA;
  });
  notify();
}

// Admin only: fetch every message directly from the DB (bypasses house cache).
// Returns rows ordered by created_at desc. Includes broadcasts.
export async function adminFetchAllMessages({ limit = 2000 } = {}) {
  const { data, error } = await supabase
    .from("chat_messages")
    .select("id, from_house, to_house, body, created_at")
    .order("created_at", { ascending: false })
    .limit(limit);
  if (error) throw error;
  return data ?? [];
}

// Admin only: list every distinct direct conversation as a sorted house pair.
// Returns [{ a, b, count, lastAt }] (a < b). Broadcasts are excluded.
export async function adminListDirectConversations() {
  const rows = await adminFetchAllMessages({ limit: 5000 });
  const pairs = new Map();
  for (const r of rows) {
    if (r.to_house === null) continue;
    const [a, b] = [r.from_house, r.to_house].sort();
    const key = `${a}|${b}`;
    const entry = pairs.get(key) ?? { a, b, count: 0, lastAt: r.created_at };
    entry.count += 1;
    if (Date.parse(r.created_at) > Date.parse(entry.lastAt)) entry.lastAt = r.created_at;
    pairs.set(key, entry);
  }
  return [...pairs.values()].sort(
    (x, y) => Date.parse(y.lastAt) - Date.parse(x.lastAt)
  );
}

// Admin only: count broadcast messages currently in the DB.
export async function adminCountBroadcasts() {
  const { count, error } = await supabase
    .from("chat_messages")
    .select("id", { count: "exact", head: true })
    .is("to_house", null);
  if (error) throw error;
  return count ?? 0;
}
