// Web Push subscription. Optional: chat works without it. When the user
// installs the PWA and opts in, the browser is registered with Supabase so
// a server-side delivery function (see SQL/Edge Function notes below) can
// push notifications to that device when a message arrives for its house.
//
// ---------------------------------------------------------------------------
// SQL setup:
//
//   create table if not exists push_subscriptions (
//     id          bigint generated by default as identity primary key,
//     house       text not null,
//     endpoint    text not null unique,
//     p256dh      text not null,
//     auth        text not null,
//     user_agent  text,
//     created_at  timestamptz default now()
//   );
//   create index if not exists push_subscriptions_house_idx
//     on push_subscriptions (house);
//   alter table push_subscriptions enable row level security;
//   create policy "anyone can insert"  on push_subscriptions for insert with check (true);
//   create policy "anyone can delete"  on push_subscriptions for delete using (true);
//
// VAPID keys (generate once with `npx web-push generate-vapid-keys`):
//   - PUBLIC key  -> paste below into VAPID_PUBLIC_KEY
//   - PRIVATE key -> Supabase Edge Function secret (never in client code)
//
// Edge Function (Deno) sketch — deploy as `send-chat-push`, trigger from a
// `chat_messages` insert webhook or a database trigger that calls it:
//
//   import webpush from "https://esm.sh/web-push@3";
//   webpush.setVapidDetails("mailto:you@example.com", PUBLIC, PRIVATE);
//   const subs = await db.from("push_subscriptions")
//     .select("*").or(`house.eq.${row.to_house},and(house.neq.${row.from_house})`);
//   for (const s of subs.data) {
//     await webpush.sendNotification(
//       { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
//       JSON.stringify({ from: row.from_house, to: row.to_house, body: row.body })
//     ).catch(() => db.from("push_subscriptions").delete().eq("endpoint", s.endpoint));
//   }
// ---------------------------------------------------------------------------

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./supabaseConfig.js?v=1778408805";
import { getCurrentHouse } from "./currentHouse.js?v=1778408805";

// VAPID public key. Empty = push disabled (the UI hides the toggle and the
// rest of the app works normally). The matching PRIVATE key lives only as a
// Supabase Edge Function secret — never commit it.
export const VAPID_PUBLIC_KEY =
  "BH_vBmhYlmGF9uCRJbCJczTFbyAGQpYDEm57mqTzcXotJemC3L0KX7qWIoDLuncSA89ijBghp1TBpc2ik6x6hJc";

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: { persistSession: false },
});

export function isPushConfigured() {
  return !!VAPID_PUBLIC_KEY;
}

export function isPushSupported() {
  return (
    isPushConfigured() &&
    typeof window !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

export async function getCurrentSubscription() {
  if (!isPushSupported()) return null;
  const reg = await navigator.serviceWorker.getRegistration();
  if (!reg) return null;
  return reg.pushManager.getSubscription();
}

export async function isSubscribed() {
  const sub = await getCurrentSubscription();
  return !!sub;
}

export async function subscribePush() {
  if (!isPushSupported()) throw new Error("Push støttes ikke i denne nettleseren");
  const house = getCurrentHouse();
  if (!house) throw new Error("Velg hus først");

  const permission = await Notification.requestPermission();
  if (permission !== "granted") throw new Error("Tillatelse ikke gitt");

  const reg = await navigator.serviceWorker.ready;
  let sub = await reg.pushManager.getSubscription();
  if (!sub) {
    sub = await reg.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
    });
  }

  const json = sub.toJSON();
  const { error } = await supabase
    .from("push_subscriptions")
    .upsert(
      {
        house,
        endpoint: json.endpoint,
        p256dh: json.keys.p256dh,
        auth: json.keys.auth,
        user_agent: navigator.userAgent.slice(0, 250),
      },
      { onConflict: "endpoint" }
    );
  if (error) throw error;
  return sub;
}

export async function unsubscribePush() {
  const sub = await getCurrentSubscription();
  if (!sub) return;
  const endpoint = sub.endpoint;
  try { await sub.unsubscribe(); } catch {}
  try {
    await supabase.from("push_subscriptions").delete().eq("endpoint", endpoint);
  } catch {}
}

function urlBase64ToUint8Array(base64String) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}
