-- ---------------------------------------------------------------------------
-- Sameieboden chat + push setup. Run this once in the Supabase SQL editor.
-- Idempotent (safe to re-run).
-- ---------------------------------------------------------------------------

-- 1. chat_messages -----------------------------------------------------------
create table if not exists chat_messages (
  id          bigint generated by default as identity primary key,
  from_house  text not null,
  to_house    text,                       -- null => broadcast ("Sameiet")
  body        text not null,
  created_at  timestamptz default now()
);
create index if not exists chat_messages_to_idx     on chat_messages (to_house, created_at desc);
create index if not exists chat_messages_from_idx   on chat_messages (from_house, created_at desc);
create index if not exists chat_messages_recent_idx on chat_messages (created_at desc);

alter table chat_messages enable row level security;
drop policy if exists "anyone can read chat"   on chat_messages;
drop policy if exists "anyone can insert chat" on chat_messages;
drop policy if exists "anyone can delete chat" on chat_messages;
create policy "anyone can read chat"   on chat_messages for select using (true);
create policy "anyone can insert chat" on chat_messages for insert with check (true);
create policy "anyone can delete chat" on chat_messages for delete using (true);

-- Realtime
alter publication supabase_realtime add table chat_messages;

-- 2. push_subscriptions ------------------------------------------------------
create table if not exists push_subscriptions (
  id         bigint generated by default as identity primary key,
  house      text not null,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  user_agent text,
  created_at timestamptz default now()
);
create index if not exists push_subscriptions_house_idx on push_subscriptions (house);

alter table push_subscriptions enable row level security;
drop policy if exists "anyone can insert subs" on push_subscriptions;
drop policy if exists "anyone can upsert subs" on push_subscriptions;
drop policy if exists "anyone can delete subs" on push_subscriptions;
create policy "anyone can insert subs" on push_subscriptions for insert with check (true);
create policy "anyone can upsert subs" on push_subscriptions for update using (true) with check (true);
create policy "anyone can delete subs" on push_subscriptions for delete using (true);

-- 3. Trigger: when a chat message is inserted, call the Edge Function -------
-- Requires the `pg_net` extension (enabled by default on Supabase).
create extension if not exists pg_net;

-- Replace these two values, then re-run this section:
--   <PROJECT_REF>   e.g. abcdwxyz   (from your Supabase project URL)
--   <SERVICE_ROLE>  service_role key from Project Settings → API
-- The trigger uses the service-role key so the Edge Function can be invoked
-- without exposing it to the browser.

create or replace function notify_chat_push() returns trigger as $$
declare
  function_url text := 'https://<PROJECT_REF>.functions.supabase.co/send-chat-push';
  service_key  text := '<SERVICE_ROLE>';
begin
  perform net.http_post(
    url     := function_url,
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || service_key
    ),
    body    := jsonb_build_object(
      'id',         new.id,
      'from_house', new.from_house,
      'to_house',   new.to_house,
      'body',       new.body
    )
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists chat_messages_push on chat_messages;
create trigger chat_messages_push
  after insert on chat_messages
  for each row execute function notify_chat_push();
