-- ---------------------------------------------------------------------------
-- Sameieboden — privacy-respecting house-pick analytics.
-- Run once in the Supabase SQL editor. Idempotent (safe to re-run).
--
-- What this stores: which house number a visitor selected in the "Hvilket
-- hus er du?" picker, plus broad device/locale info that is already
-- available in the browser (user-agent, language, timezone, screen size,
-- referrer, PWA install state).
--
-- What this does NOT store: IP address, GPS coordinates, persistent
-- visitor id, cookies, or anything that uniquely identifies a person.
-- Country/region is approximated only via timezone + browser language.
-- ---------------------------------------------------------------------------

create table if not exists house_picks (
  id              bigint generated by default as identity primary key,
  house           text not null,
  previous_house  text,                 -- null on first-ever pick on this device
  source          text default 'pick',  -- 'pick' (user clicked a house) or 'open' (page open)
  user_agent      text,
  language        text,
  timezone        text,
  screen_size     text,                 -- "390x844" etc
  referrer        text,
  is_pwa          boolean default false,
  created_at      timestamptz default now()
);

-- Add the column on existing installs (idempotent).
alter table house_picks add column if not exists source text default 'pick';

create index if not exists house_picks_created_idx on house_picks (created_at desc);
create index if not exists house_picks_house_idx   on house_picks (house, created_at desc);
create index if not exists house_picks_source_idx  on house_picks (source, created_at desc);

alter table house_picks enable row level security;

drop policy if exists "anyone can insert house picks" on house_picks;
drop policy if exists "anyone can read house picks"   on house_picks;
drop policy if exists "anyone can delete house picks" on house_picks;

-- Anyone can write (anon-key insert from the browser) and read (so the
-- localhost-only admin page can list them via the same anon key).
create policy "anyone can insert house picks" on house_picks for insert with check (true);
create policy "anyone can read house picks"   on house_picks for select using (true);
create policy "anyone can delete house picks" on house_picks for delete using (true);
